import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/util/views/banner";
import { Container, Row, Col } from "react-bootstrap";
import CooperationSlider from "../components/util/views/CooperationSlider";
import Carousel from "../components/util/views/carousel";
//==========================================================
export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Khairshoor</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container>
          <main className={styles.main}> </main>{" "}
          <footer className={styles.footer}>
            <CooperationSlider />{" "}
          </footer>
        </Container>
      </div>
    </>
  );
}
